/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUnidadesRouteImport } from './routes/_authenticated/unidades'
import { Route as AuthenticatedLicencasRouteImport } from './routes/_authenticated/licencas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedUnidadesIdRouteImport } from './routes/_authenticated/unidades.$id'
import { Route as ApiPublicHooksEnviarAlertasRouteImport } from './routes/api/public/hooks/enviar-alertas'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnidadesRoute = AuthenticatedUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicencasRoute = AuthenticatedLicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnidadesIdRoute = AuthenticatedUnidadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedUnidadesRoute,
} as any)
const ApiPublicHooksEnviarAlertasRoute =
  ApiPublicHooksEnviarAlertasRouteImport.update({
    id: '/api/public/hooks/enviar-alertas',
    path: '/api/public/hooks/enviar-alertas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/licencas': typeof AuthenticatedLicencasRoute
  '/unidades': typeof AuthenticatedUnidadesRouteWithChildren
  '/unidades/$id': typeof AuthenticatedUnidadesIdRoute
  '/api/public/hooks/enviar-alertas': typeof ApiPublicHooksEnviarAlertasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/licencas': typeof AuthenticatedLicencasRoute
  '/unidades': typeof AuthenticatedUnidadesRouteWithChildren
  '/unidades/$id': typeof AuthenticatedUnidadesIdRoute
  '/api/public/hooks/enviar-alertas': typeof ApiPublicHooksEnviarAlertasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/licencas': typeof AuthenticatedLicencasRoute
  '/_authenticated/unidades': typeof AuthenticatedUnidadesRouteWithChildren
  '/_authenticated/unidades/$id': typeof AuthenticatedUnidadesIdRoute
  '/api/public/hooks/enviar-alertas': typeof ApiPublicHooksEnviarAlertasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/calendario'
    | '/dashboard'
    | '/licencas'
    | '/unidades'
    | '/unidades/$id'
    | '/api/public/hooks/enviar-alertas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/calendario'
    | '/dashboard'
    | '/licencas'
    | '/unidades'
    | '/unidades/$id'
    | '/api/public/hooks/enviar-alertas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/calendario'
    | '/_authenticated/dashboard'
    | '/_authenticated/licencas'
    | '/_authenticated/unidades'
    | '/_authenticated/unidades/$id'
    | '/api/public/hooks/enviar-alertas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksEnviarAlertasRoute: typeof ApiPublicHooksEnviarAlertasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/unidades': {
      id: '/_authenticated/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof AuthenticatedUnidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licencas': {
      id: '/_authenticated/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof AuthenticatedLicencasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unidades/$id': {
      id: '/_authenticated/unidades/$id'
      path: '/$id'
      fullPath: '/unidades/$id'
      preLoaderRoute: typeof AuthenticatedUnidadesIdRouteImport
      parentRoute: typeof AuthenticatedUnidadesRoute
    }
    '/api/public/hooks/enviar-alertas': {
      id: '/api/public/hooks/enviar-alertas'
      path: '/api/public/hooks/enviar-alertas'
      fullPath: '/api/public/hooks/enviar-alertas'
      preLoaderRoute: typeof ApiPublicHooksEnviarAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedUnidadesRouteChildren {
  AuthenticatedUnidadesIdRoute: typeof AuthenticatedUnidadesIdRoute
}

const AuthenticatedUnidadesRouteChildren: AuthenticatedUnidadesRouteChildren = {
  AuthenticatedUnidadesIdRoute: AuthenticatedUnidadesIdRoute,
}

const AuthenticatedUnidadesRouteWithChildren =
  AuthenticatedUnidadesRoute._addFileChildren(
    AuthenticatedUnidadesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLicencasRoute: typeof AuthenticatedLicencasRoute
  AuthenticatedUnidadesRoute: typeof AuthenticatedUnidadesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLicencasRoute: AuthenticatedLicencasRoute,
  AuthenticatedUnidadesRoute: AuthenticatedUnidadesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksEnviarAlertasRoute: ApiPublicHooksEnviarAlertasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
